ASN_MODULE_SOURCES=	\
	DateTime.c	\
	LocalTimeStamp.c	\
	DataInterChange.c	\
	TransferBatch.c	\
	Notification.c	\
	CallEventDetailList.c	\
	CallEventDetail.c	\
	BatchControlInfo.c	\
	AccountingInfo.c	\
	NetworkInfo.c	\
	VasInfo.c	\
	MessageDescriptionInfo.c	\
	MobileOriginatedCall.c	\
	MobileTerminatedCall.c	\
	SupplServiceEvent.c	\
	ServiceCentreUsage.c	\
	ValueAddedService.c	\
	GprsCall.c	\
	ContentTransaction.c	\
	LocationService.c	\
	AuditControlInfo.c	\
	ThreeGCamelDestination.c	\
	AccessPointNameNI.c	\
	AccessPointNameOI.c	\
	AccessPointName.c	\
	AiurRequested.c	\
	BasicHSCSDParameters.c	\
	AddressStringDigits.c	\
	AgeOfLocation.c	\
	BasicService.c	\
	BasicServiceCode.c	\
	BasicServiceCodeList.c	\
	BasicServiceUsedList.c	\
	BasicServiceUsed.c	\
	BearerServiceCode.c	\
	CalledNumAnalysis.c	\
	CalledNumAnalysisCode.c	\
	CalledNumAnalysisList.c	\
	CallOriginator.c	\
	CalledPlace.c	\
	CallEventDetailsCount.c	\
	CallEventStartTimeStamp.c	\
	CallReference.c	\
	CalledRegion.c	\
	CallType.c	\
	CallTypeSubtype.c	\
	CallTypeGroup.c	\
	CallTypeLevel1.c	\
	CallTypeLevel2.c	\
	CallTypeLevel3.c	\
	CalledCountryCode.c	\
	CamelCallReference.c	\
	CamelCallReferenceNumber.c	\
	CamelDestination.c	\
	CamelInitiatedCFIndicator.c	\
	CamelModification.c	\
	CamelServerAddress.c	\
	CamelModificationList.c	\
	CamelServiceKey.c	\
	CamelServiceLevel.c	\
	CamelServiceUsed.c	\
	CauseForTerm.c	\
	CellId.c	\
	ChannelCoding.c	\
	ChannelCodingsAcceptable.c	\
	Charge.c	\
	ChargeDetail.c	\
	ChargeDetailList.c	\
	ChargeableSubscriber.c	\
	ChargeableUnits.c	\
	ChargedItem.c	\
	ChargedPartyStatus.c	\
	ChargedUnits.c	\
	ChargeInformation.c	\
	ChargeInformationList.c	\
	ChargeType.c	\
	ChargingCharacteristics.c	\
	ChargingId.c	\
	ChargingPoint.c	\
	ChargingTimeStamp.c	\
	ClirIndicator.c	\
	CompletionTimeStamp.c	\
	ContentProviderIdType.c	\
	ContentProviderIdentifier.c	\
	CountryCode.c	\
	CountryCodeTable.c	\
	CseInformation.c	\
	CurrencyConversion.c	\
	CustomerIdType.c	\
	CustomerIdentifier.c	\
	DataVolume.c	\
	DataVolumeIncoming.c	\
	DataVolumeOutgoing.c	\
	DataVolumeReference.c	\
	DateTimeLong.c	\
	DayCategory.c	\
	DayCategorySubtype.c	\
	DefaultCallHandlingIndicator.c	\
	DepositTimeStamp.c	\
	Destination.c	\
	DestinationNetwork.c	\
	DialledDigits.c	\
	DiscountCode.c	\
	DiscountRate.c	\
	DiscountValue.c	\
	DiscountApplied.c	\
	DiscountDefinition.c	\
	Discounting.c	\
	DiscountInformation.c	\
	DiscountInformationList.c	\
	DistanceChargeBandCode.c	\
	DualServiceCode.c	\
	DualBearerServiceCode.c	\
	DualTeleServiceCode.c	\
	EarliestCallTimeStamp.c	\
	EquipmentInformation.c	\
	Esn.c	\
	ExchangeRate.c	\
	ExchangeRateCode.c	\
	ExchangeRateDefinition.c	\
	FileAvailableTimeStamp.c	\
	FileCreationTimeStamp.c	\
	FileSequenceNumber.c	\
	FileTypeIndicator.c	\
	Fnur.c	\
	FraudMonitorIndicator.c	\
	GeographicalLocation.c	\
	GprsBasicCallInformation.c	\
	GprsChargeableSubscriber.c	\
	GprsDestination.c	\
	GprsLocationInformation.c	\
	GprsNetworkLocation.c	\
	GprsServiceUsage.c	\
	GprsServiceUsageList.c	\
	GprsServiceUsed.c	\
	GsmChargeableSubscriber.c	\
	GsnAddress.c	\
	HomeBid.c	\
	HomeLocationInformation.c	\
	HorizontalAccuracyDelivered.c	\
	HorizontalAccuracyRequested.c	\
	HSCSDInformation.c	\
	HSCSDParameterModification.c	\
	HSCSDParameterModificationList.c	\
	Iac.c	\
	IacTable.c	\
	Imei.c	\
	ImeiOrEsn.c	\
	Imsi.c	\
	InitiatingParty.c	\
	ISPList.c	\
	IpAddress.c	\
	IPTextV4Address.c	\
	IPTextV6Address.c	\
	LatestCallTimeStamp.c	\
	Latitude.c	\
	LocalCurrency.c	\
	LocationArea.c	\
	LocationDescription.c	\
	LocationInformation.c	\
	Longitude.c	\
	LCSQosDelivered.c	\
	LCSQosRequested.c	\
	LCSRequestTimestamp.c	\
	LCSSPInformation.c	\
	LCSSPIdentificationList.c	\
	LCSSPIdentification.c	\
	LCSTransactionStatus.c	\
	LocationServiceUsage.c	\
	Mdn.c	\
	MinChargeableSubscriber.c	\
	MessageDescriptionCode.c	\
	MessageDescription.c	\
	MessageDescriptionDefinition.c	\
	MessageStatus.c	\
	MessageType.c	\
	Min.c	\
	MoBasicCallInformation.c	\
	MobileStationClassMark.c	\
	ModificationIndicator.c	\
	ModificationTimestamp.c	\
	MscId.c	\
	Msisdn.c	\
	MtBasicCallInformation.c	\
	MultiRateIndicator.c	\
	NetworkId.c	\
	NetworkLocation.c	\
	NetworkInitPDPContext.c	\
	NetworkType.c	\
	NonChargedParty.c	\
	NumberOfDecimalPlaces.c	\
	NumberingPlan.c	\
	NumberOfChannels.c	\
	ObjectType.c	\
	OperatorSpecInformation.c	\
	OperatorSpecInfoList.c	\
	OriginatingNetwork.c	\
	PacketDataProtocolAddress.c	\
	PartialTypeIndicator.c	\
	PdpAddress.c	\
	PDPContextStartTimestamp.c	\
	PdpType.c	\
	PlmnId.c	\
	PositioningMethod.c	\
	PriorityCode.c	\
	QoSInformation.c	\
	QoSDelay.c	\
	QoSGuaranteedBitRateDownlink.c	\
	QoSGuaranteedBitRateUplink.c	\
	QoSMeanThroughput.c	\
	QoSPeakThroughput.c	\
	QoSPrecedence.c	\
	QoSReliability.c	\
	RadioChannelRequested.c	\
	RadioChannelUsed.c	\
	QoSAllocRetenPriority.c	\
	QoSDeliveryOrder.c	\
	QoSErroneousSDUs.c	\
	QoSHandlingpriority.c	\
	QoSMaxBitRate.c	\
	QoSMaxBitRateUplink.c	\
	QoSMaxBitRateDownlink.c	\
	QoSMaxSDUsize.c	\
	QoSResidualBER.c	\
	QoSSDUErrorRatio.c	\
	QoSTrafficClass.c	\
	QoSTransferDelay.c	\
	GSMQoSRequested.c	\
	GSMQoSUsed.c	\
	QoSRequestedV37.c	\
	QoSUsedV37.c	\
	QoSRequestedV38.c	\
	QoSUsedV38.c	\
	UMTSQoSInformation.c	\
	UMTSQoSRequested.c	\
	UMTSQoSUsed.c	\
	UserProtocolIndicator.c	\
	RapFileSequenceNumber.c	\
	Recipient.c	\
	RecEntityDefinition.c	\
	RecEntityCode.c	\
	RecEntityCodeList.c	\
	RecEntityType.c	\
	RecEntityId.c	\
	RecEntityTable.c	\
	ReleaseVersionNumber.c	\
	RemotePdpAddressList.c	\
	ResponseTime.c	\
	ResponseTimeCategory.c	\
	ScuBasicInformation.c	\
	ScuChargeType.c	\
	ScuTimeStamps.c	\
	ScuVasChargeableSubscriber.c	\
	Sender.c	\
	ServiceCentreIdentity.c	\
	ServingBid.c	\
	ServingNetwork.c	\
	SimChargeableSubscriber.c	\
	SimToolkitIndicator.c	\
	SpecificationVersionNumber.c	\
	SpeechVersionRequested.c	\
	SpeechVersionUsed.c	\
	SpeechVersion.c	\
	SsParameters.c	\
	SupplServiceUsed.c	\
	SupplServiceUsedList.c	\
	SupplServiceActionCode.c	\
	SupplServiceCode.c	\
	TapCurrency.c	\
	Taxation.c	\
	TaxCode.c	\
	TapDecimalPlaces.c	\
	TaxInformation.c	\
	TaxInformationList.c	\
	TaxValue10.c	\
	TaxRate.c	\
	TaxableAmount.c	\
	TaxRateDefinition.c	\
	TaxType.c	\
	TeleServiceCode.c	\
	ThirdPartyInformation.c	\
	TimeBand.c	\
	TimeBandSubtype.c	\
	TotalChargeValue.c	\
	TotalCallEventDuration.c	\
	TotalChargeValueList.c	\
	TotalDiscountValue.c	\
	TotalTaxValue.c	\
	TrackedCustomerInformation.c	\
	TrackedCustomerIdList.c	\
	TrackedCustomerIdentification.c	\
	TrackedCustomerHomeIdList.c	\
	TrackedCustomerHomeId.c	\
	HomeIdentifier.c	\
	TrackedCustomerLocList.c	\
	TrackedCustomerLocation.c	\
	TrackedCustomerEquipment.c	\
	TrackingCustomerInformation.c	\
	TrackingCustomerIdList.c	\
	TrackingCustomerIdentification.c	\
	TrackingCustomerHomeIdList.c	\
	TrackingCustomerHomeId.c	\
	TrackingCustomerLocList.c	\
	TrackingCustomerLocation.c	\
	TrackingCustomerEquipment.c	\
	TrackingFrequency.c	\
	TrackingPeriod.c	\
	TransferCutOffTimeStamp.c	\
	TransparencyIndicator.c	\
	TypeOfControllingNode.c	\
	TypeOfNumber.c	\
	UtcTimeOffset.c	\
	UtcTimeOffsetCode.c	\
	UtcTimeOffsetDefinition.c	\
	UtcTimeOffsetInfo.c	\
	ValueAddedServiceUsedList.c	\
	ValueAddedServiceUsed.c	\
	VasCode.c	\
	VasDefinition.c	\
	VasDescription.c	\
	VasShortDescription.c	\
	VerticalAccuracyDelivered.c	\
	VerticalAccuracyRequested.c	\
	AbsoluteAmount.c	\
	Bid.c	\
	Code.c	\
	Currency.c	\
	AsciiString.c	\
	Description.c	\
	TapHexString.c	\
	PercentageRate.c	\
	BCDString.c	\
	OrderPlacementTimeStamp.c	\
	RequestedDeliveryTimeStamp.c	\
	ActualDeliveryTimeStamp.c	\
	TransactionStatus.c	\
	ContentTransactionBasicInfo.c	\
	ChargedPartyIdType.c	\
	LoginName.c	\
	AccountNumber.c	\
	EmailAddress.c	\
	ChargedPartyIdentification.c	\
	ChargedPartyId.c	\
	ChargedPartyIdList.c	\
	HomeIdType.c	\
	Name.c	\
	ChargedPartyHomeId.c	\
	ChargedPartyHomeIdList.c	\
	LocationIdType.c	\
	LocationIdentifier.c	\
	CountryName.c	\
	CountryAsciCode.c	\
	TapRegion.c	\
	Place.c	\
	ChargedPartyLocation.c	\
	ChargedPartyLocationList.c	\
	EquipmentIdType.c	\
	EquipmentId.c	\
	ChargedPartyEquipment.c	\
	ChargedPartyInformation.c	\
	ProviderIdType.c	\
	Url.c	\
	ProviderId.c	\
	ContentProviderId.c	\
	ContentProviderIdList.c	\
	InternetServiceProviderId.c	\
	InternetServiceProviderIdList.c	\
	NetworkIdType.c	\
	NetworkDesc.c	\
	NetworkIdentifier.c	\
	NetworkIdGroup.c	\
	NetworkIdList.c	\
	ContentProviderName.c	\
	ServingPartiesInformation.c	\
	ContentTransactionCode.c	\
	ContentTransactionType.c	\
	TransactionDescriptionSupp.c	\
	TransactionDetailDescription.c	\
	TransactionShortDescription.c	\
	TransactionIdentifier.c	\
	TransactionAuthCode.c	\
	TotalDataVolume.c	\
	ChargeRefundIndicator.c	\
	ContentChargingPoint.c	\
	PaidIndicator.c	\
	PaymentMethod.c	\
	AdvisedChargeCurrency.c	\
	AdvisedCharge.c	\
	Commission.c	\
	AdvisedChargeInformation.c	\
	ContentServiceUsed.c	\
	ContentServiceUsedList.c	\
	TotalTaxRefund.c	\
	TotalDiscountRefund.c	\
	TotalChargeRefund.c	\
	TotalAdvisedCharge.c	\
	TotalAdvisedChargeRefund.c	\
	TotalCommission.c	\
	TotalCommissionRefund.c	\
	TotalAdvisedChargeValue.c	\
	TotalAdvisedChargeValueList.c

ASN_MODULE_HEADERS=	\
	DateTime.h	\
	LocalTimeStamp.h	\
	DataInterChange.h	\
	TransferBatch.h	\
	Notification.h	\
	CallEventDetailList.h	\
	CallEventDetail.h	\
	BatchControlInfo.h	\
	AccountingInfo.h	\
	NetworkInfo.h	\
	VasInfo.h	\
	MessageDescriptionInfo.h	\
	MobileOriginatedCall.h	\
	MobileTerminatedCall.h	\
	SupplServiceEvent.h	\
	ServiceCentreUsage.h	\
	ValueAddedService.h	\
	GprsCall.h	\
	ContentTransaction.h	\
	LocationService.h	\
	AuditControlInfo.h	\
	ThreeGCamelDestination.h	\
	AccessPointNameNI.h	\
	AccessPointNameOI.h	\
	AccessPointName.h	\
	AiurRequested.h	\
	BasicHSCSDParameters.h	\
	AddressStringDigits.h	\
	AgeOfLocation.h	\
	BasicService.h	\
	BasicServiceCode.h	\
	BasicServiceCodeList.h	\
	BasicServiceUsedList.h	\
	BasicServiceUsed.h	\
	BearerServiceCode.h	\
	CalledNumAnalysis.h	\
	CalledNumAnalysisCode.h	\
	CalledNumAnalysisList.h	\
	CallOriginator.h	\
	CalledPlace.h	\
	CallEventDetailsCount.h	\
	CallEventStartTimeStamp.h	\
	CallReference.h	\
	CalledRegion.h	\
	CallType.h	\
	CallTypeSubtype.h	\
	CallTypeGroup.h	\
	CallTypeLevel1.h	\
	CallTypeLevel2.h	\
	CallTypeLevel3.h	\
	CalledCountryCode.h	\
	CamelCallReference.h	\
	CamelCallReferenceNumber.h	\
	CamelDestination.h	\
	CamelInitiatedCFIndicator.h	\
	CamelModification.h	\
	CamelServerAddress.h	\
	CamelModificationList.h	\
	CamelServiceKey.h	\
	CamelServiceLevel.h	\
	CamelServiceUsed.h	\
	CauseForTerm.h	\
	CellId.h	\
	ChannelCoding.h	\
	ChannelCodingsAcceptable.h	\
	Charge.h	\
	ChargeDetail.h	\
	ChargeDetailList.h	\
	ChargeableSubscriber.h	\
	ChargeableUnits.h	\
	ChargedItem.h	\
	ChargedPartyStatus.h	\
	ChargedUnits.h	\
	ChargeInformation.h	\
	ChargeInformationList.h	\
	ChargeType.h	\
	ChargingCharacteristics.h	\
	ChargingId.h	\
	ChargingPoint.h	\
	ChargingTimeStamp.h	\
	ClirIndicator.h	\
	CompletionTimeStamp.h	\
	ContentProviderIdType.h	\
	ContentProviderIdentifier.h	\
	CountryCode.h	\
	CountryCodeTable.h	\
	CseInformation.h	\
	CurrencyConversion.h	\
	CustomerIdType.h	\
	CustomerIdentifier.h	\
	DataVolume.h	\
	DataVolumeIncoming.h	\
	DataVolumeOutgoing.h	\
	DataVolumeReference.h	\
	DateTimeLong.h	\
	DayCategory.h	\
	DayCategorySubtype.h	\
	DefaultCallHandlingIndicator.h	\
	DepositTimeStamp.h	\
	Destination.h	\
	DestinationNetwork.h	\
	DialledDigits.h	\
	DiscountCode.h	\
	DiscountRate.h	\
	DiscountValue.h	\
	DiscountApplied.h	\
	DiscountDefinition.h	\
	Discounting.h	\
	DiscountInformation.h	\
	DiscountInformationList.h	\
	DistanceChargeBandCode.h	\
	DualServiceCode.h	\
	DualBearerServiceCode.h	\
	DualTeleServiceCode.h	\
	EarliestCallTimeStamp.h	\
	EquipmentInformation.h	\
	Esn.h	\
	ExchangeRate.h	\
	ExchangeRateCode.h	\
	ExchangeRateDefinition.h	\
	FileAvailableTimeStamp.h	\
	FileCreationTimeStamp.h	\
	FileSequenceNumber.h	\
	FileTypeIndicator.h	\
	Fnur.h	\
	FraudMonitorIndicator.h	\
	GeographicalLocation.h	\
	GprsBasicCallInformation.h	\
	GprsChargeableSubscriber.h	\
	GprsDestination.h	\
	GprsLocationInformation.h	\
	GprsNetworkLocation.h	\
	GprsServiceUsage.h	\
	GprsServiceUsageList.h	\
	GprsServiceUsed.h	\
	GsmChargeableSubscriber.h	\
	GsnAddress.h	\
	HomeBid.h	\
	HomeLocationInformation.h	\
	HorizontalAccuracyDelivered.h	\
	HorizontalAccuracyRequested.h	\
	HSCSDInformation.h	\
	HSCSDParameterModification.h	\
	HSCSDParameterModificationList.h	\
	Iac.h	\
	IacTable.h	\
	Imei.h	\
	ImeiOrEsn.h	\
	Imsi.h	\
	InitiatingParty.h	\
	ISPList.h	\
	IpAddress.h	\
	IPTextV4Address.h	\
	IPTextV6Address.h	\
	LatestCallTimeStamp.h	\
	Latitude.h	\
	LocalCurrency.h	\
	LocationArea.h	\
	LocationDescription.h	\
	LocationInformation.h	\
	Longitude.h	\
	LCSQosDelivered.h	\
	LCSQosRequested.h	\
	LCSRequestTimestamp.h	\
	LCSSPInformation.h	\
	LCSSPIdentificationList.h	\
	LCSSPIdentification.h	\
	LCSTransactionStatus.h	\
	LocationServiceUsage.h	\
	Mdn.h	\
	MinChargeableSubscriber.h	\
	MessageDescriptionCode.h	\
	MessageDescription.h	\
	MessageDescriptionDefinition.h	\
	MessageStatus.h	\
	MessageType.h	\
	Min.h	\
	MoBasicCallInformation.h	\
	MobileStationClassMark.h	\
	ModificationIndicator.h	\
	ModificationTimestamp.h	\
	MscId.h	\
	Msisdn.h	\
	MtBasicCallInformation.h	\
	MultiRateIndicator.h	\
	NetworkId.h	\
	NetworkLocation.h	\
	NetworkInitPDPContext.h	\
	NetworkType.h	\
	NonChargedParty.h	\
	NumberOfDecimalPlaces.h	\
	NumberingPlan.h	\
	NumberOfChannels.h	\
	ObjectType.h	\
	OperatorSpecInformation.h	\
	OperatorSpecInfoList.h	\
	OriginatingNetwork.h	\
	PacketDataProtocolAddress.h	\
	PartialTypeIndicator.h	\
	PdpAddress.h	\
	PDPContextStartTimestamp.h	\
	PdpType.h	\
	PlmnId.h	\
	PositioningMethod.h	\
	PriorityCode.h	\
	QoSInformation.h	\
	QoSDelay.h	\
	QoSGuaranteedBitRateDownlink.h	\
	QoSGuaranteedBitRateUplink.h	\
	QoSMeanThroughput.h	\
	QoSPeakThroughput.h	\
	QoSPrecedence.h	\
	QoSReliability.h	\
	RadioChannelRequested.h	\
	RadioChannelUsed.h	\
	QoSAllocRetenPriority.h	\
	QoSDeliveryOrder.h	\
	QoSErroneousSDUs.h	\
	QoSHandlingpriority.h	\
	QoSMaxBitRate.h	\
	QoSMaxBitRateUplink.h	\
	QoSMaxBitRateDownlink.h	\
	QoSMaxSDUsize.h	\
	QoSResidualBER.h	\
	QoSSDUErrorRatio.h	\
	QoSTrafficClass.h	\
	QoSTransferDelay.h	\
	GSMQoSRequested.h	\
	GSMQoSUsed.h	\
	QoSRequestedV37.h	\
	QoSUsedV37.h	\
	QoSRequestedV38.h	\
	QoSUsedV38.h	\
	UMTSQoSInformation.h	\
	UMTSQoSRequested.h	\
	UMTSQoSUsed.h	\
	UserProtocolIndicator.h	\
	RapFileSequenceNumber.h	\
	Recipient.h	\
	RecEntityDefinition.h	\
	RecEntityCode.h	\
	RecEntityCodeList.h	\
	RecEntityType.h	\
	RecEntityId.h	\
	RecEntityTable.h	\
	ReleaseVersionNumber.h	\
	RemotePdpAddressList.h	\
	ResponseTime.h	\
	ResponseTimeCategory.h	\
	ScuBasicInformation.h	\
	ScuChargeType.h	\
	ScuTimeStamps.h	\
	ScuVasChargeableSubscriber.h	\
	Sender.h	\
	ServiceCentreIdentity.h	\
	ServingBid.h	\
	ServingNetwork.h	\
	SimChargeableSubscriber.h	\
	SimToolkitIndicator.h	\
	SpecificationVersionNumber.h	\
	SpeechVersionRequested.h	\
	SpeechVersionUsed.h	\
	SpeechVersion.h	\
	SsParameters.h	\
	SupplServiceUsed.h	\
	SupplServiceUsedList.h	\
	SupplServiceActionCode.h	\
	SupplServiceCode.h	\
	TapCurrency.h	\
	Taxation.h	\
	TaxCode.h	\
	TapDecimalPlaces.h	\
	TaxInformation.h	\
	TaxInformationList.h	\
	TaxValue10.h	\
	TaxRate.h	\
	TaxableAmount.h	\
	TaxRateDefinition.h	\
	TaxType.h	\
	TeleServiceCode.h	\
	ThirdPartyInformation.h	\
	TimeBand.h	\
	TimeBandSubtype.h	\
	TotalChargeValue.h	\
	TotalCallEventDuration.h	\
	TotalChargeValueList.h	\
	TotalDiscountValue.h	\
	TotalTaxValue.h	\
	TrackedCustomerInformation.h	\
	TrackedCustomerIdList.h	\
	TrackedCustomerIdentification.h	\
	TrackedCustomerHomeIdList.h	\
	TrackedCustomerHomeId.h	\
	HomeIdentifier.h	\
	TrackedCustomerLocList.h	\
	TrackedCustomerLocation.h	\
	TrackedCustomerEquipment.h	\
	TrackingCustomerInformation.h	\
	TrackingCustomerIdList.h	\
	TrackingCustomerIdentification.h	\
	TrackingCustomerHomeIdList.h	\
	TrackingCustomerHomeId.h	\
	TrackingCustomerLocList.h	\
	TrackingCustomerLocation.h	\
	TrackingCustomerEquipment.h	\
	TrackingFrequency.h	\
	TrackingPeriod.h	\
	TransferCutOffTimeStamp.h	\
	TransparencyIndicator.h	\
	TypeOfControllingNode.h	\
	TypeOfNumber.h	\
	UtcTimeOffset.h	\
	UtcTimeOffsetCode.h	\
	UtcTimeOffsetDefinition.h	\
	UtcTimeOffsetInfo.h	\
	ValueAddedServiceUsedList.h	\
	ValueAddedServiceUsed.h	\
	VasCode.h	\
	VasDefinition.h	\
	VasDescription.h	\
	VasShortDescription.h	\
	VerticalAccuracyDelivered.h	\
	VerticalAccuracyRequested.h	\
	AbsoluteAmount.h	\
	Bid.h	\
	Code.h	\
	Currency.h	\
	AsciiString.h	\
	Description.h	\
	TapHexString.h	\
	PercentageRate.h	\
	BCDString.h	\
	OrderPlacementTimeStamp.h	\
	RequestedDeliveryTimeStamp.h	\
	ActualDeliveryTimeStamp.h	\
	TransactionStatus.h	\
	ContentTransactionBasicInfo.h	\
	ChargedPartyIdType.h	\
	LoginName.h	\
	AccountNumber.h	\
	EmailAddress.h	\
	ChargedPartyIdentification.h	\
	ChargedPartyId.h	\
	ChargedPartyIdList.h	\
	HomeIdType.h	\
	Name.h	\
	ChargedPartyHomeId.h	\
	ChargedPartyHomeIdList.h	\
	LocationIdType.h	\
	LocationIdentifier.h	\
	CountryName.h	\
	CountryAsciCode.h	\
	TapRegion.h	\
	Place.h	\
	ChargedPartyLocation.h	\
	ChargedPartyLocationList.h	\
	EquipmentIdType.h	\
	EquipmentId.h	\
	ChargedPartyEquipment.h	\
	ChargedPartyInformation.h	\
	ProviderIdType.h	\
	Url.h	\
	ProviderId.h	\
	ContentProviderId.h	\
	ContentProviderIdList.h	\
	InternetServiceProviderId.h	\
	InternetServiceProviderIdList.h	\
	NetworkIdType.h	\
	NetworkDesc.h	\
	NetworkIdentifier.h	\
	NetworkIdGroup.h	\
	NetworkIdList.h	\
	ContentProviderName.h	\
	ServingPartiesInformation.h	\
	ContentTransactionCode.h	\
	ContentTransactionType.h	\
	TransactionDescriptionSupp.h	\
	TransactionDetailDescription.h	\
	TransactionShortDescription.h	\
	TransactionIdentifier.h	\
	TransactionAuthCode.h	\
	TotalDataVolume.h	\
	ChargeRefundIndicator.h	\
	ContentChargingPoint.h	\
	PaidIndicator.h	\
	PaymentMethod.h	\
	AdvisedChargeCurrency.h	\
	AdvisedCharge.h	\
	Commission.h	\
	AdvisedChargeInformation.h	\
	ContentServiceUsed.h	\
	ContentServiceUsedList.h	\
	TotalTaxRefund.h	\
	TotalDiscountRefund.h	\
	TotalChargeRefund.h	\
	TotalAdvisedCharge.h	\
	TotalAdvisedChargeRefund.h	\
	TotalCommission.h	\
	TotalCommissionRefund.h	\
	TotalAdvisedChargeValue.h	\
	TotalAdvisedChargeValueList.h

ASN_MODULE_HEADERS+=INTEGER.h
ASN_MODULE_SOURCES+=INTEGER.c
ASN_MODULE_HEADERS+=NumericString.h
ASN_MODULE_SOURCES+=NumericString.c
ASN_MODULE_HEADERS+=VisibleString.h
ASN_MODULE_SOURCES+=VisibleString.c
ASN_MODULE_HEADERS+=asn_SEQUENCE_OF.h
ASN_MODULE_SOURCES+=asn_SEQUENCE_OF.c
ASN_MODULE_HEADERS+=asn_SET_OF.h
ASN_MODULE_SOURCES+=asn_SET_OF.c
ASN_MODULE_HEADERS+=constr_CHOICE.h
ASN_MODULE_SOURCES+=constr_CHOICE.c
ASN_MODULE_HEADERS+=constr_SEQUENCE.h
ASN_MODULE_SOURCES+=constr_SEQUENCE.c
ASN_MODULE_HEADERS+=constr_SEQUENCE_OF.h
ASN_MODULE_SOURCES+=constr_SEQUENCE_OF.c
ASN_MODULE_HEADERS+=constr_SET_OF.h
ASN_MODULE_SOURCES+=constr_SET_OF.c
ASN_MODULE_HEADERS+=asn_application.h
ASN_MODULE_HEADERS+=asn_system.h
ASN_MODULE_HEADERS+=asn_codecs.h
ASN_MODULE_HEADERS+=asn_internal.h
ASN_MODULE_HEADERS+=OCTET_STRING.h
ASN_MODULE_SOURCES+=OCTET_STRING.c
ASN_MODULE_HEADERS+=BIT_STRING.h
ASN_MODULE_SOURCES+=BIT_STRING.c
ASN_MODULE_SOURCES+=asn_codecs_prim.c
ASN_MODULE_HEADERS+=asn_codecs_prim.h
ASN_MODULE_HEADERS+=ber_tlv_length.h
ASN_MODULE_SOURCES+=ber_tlv_length.c
ASN_MODULE_HEADERS+=ber_tlv_tag.h
ASN_MODULE_SOURCES+=ber_tlv_tag.c
ASN_MODULE_HEADERS+=ber_decoder.h
ASN_MODULE_SOURCES+=ber_decoder.c
ASN_MODULE_HEADERS+=der_encoder.h
ASN_MODULE_SOURCES+=der_encoder.c
ASN_MODULE_HEADERS+=constr_TYPE.h
ASN_MODULE_SOURCES+=constr_TYPE.c
ASN_MODULE_HEADERS+=constraints.h
ASN_MODULE_SOURCES+=constraints.c
ASN_MODULE_HEADERS+=xer_support.h
ASN_MODULE_SOURCES+=xer_support.c
ASN_MODULE_HEADERS+=xer_decoder.h
ASN_MODULE_SOURCES+=xer_decoder.c
ASN_MODULE_HEADERS+=xer_encoder.h
ASN_MODULE_SOURCES+=xer_encoder.c


lib_LTLIBRARIES=libsomething.la
libsomething_la_SOURCES=$(ASN_MODULE_SOURCES) $(ASN_MODULE_HEADERS)

# This file may be used as an input for make(3)
# Remove the lines below to convert it into a pure .am file
TARGET = tap3dump
CFLAGS += -I. -DHAVE_CONFIG_H
OBJS=${ASN_MODULE_SOURCES:.c=.o} $(TARGET).o

all: $(TARGET)

$(TARGET): ${OBJS}
	$(CC) $(CFLAGS) -o $(TARGET) ${OBJS} $(LDFLAGS) $(LIBS)

.SUFFIXES:
.SUFFIXES: .c .o

.c.o:
	$(CC) $(CFLAGS) -o $@ -c $<

clean:
	rm -f $(TARGET)
	rm -f $(OBJS)

regen: regenerate-from-asn1-source

regenerate-from-asn1-source:
	../../asn1c/asn1c -S ../../skeletons ../tap310-m.asn


../tap310-m.asn:
	@echo The ../tap3.asn1 file is not yet present.
	@echo Please read the README file on how to obtain this file.
	@exit 42

DataInterChange.c: ../tap310-m.asn regenerate.Makefile
	./regenerate.Makefile
	@touch DataInterChange.c
	make

ASN_DECODER_TEMPLATE=../../skeletons/asn-decoder-template.c
$(TARGET).o: $(ASN_DECODER_TEMPLATE)
	$(CC) $(CFLAGS) -o $(TARGET).o -c $(ASN_DECODER_TEMPLATE)

distclean: clean
	rm -f $(ASN_MODULE_SOURCES) $(ASN_MODULE_HEADERS)
	rm -f Makefile.am.sample
